### PR TITLE
feat: fix: Error thrown when we have custom profile fields

### PR DESCRIPTION
**Pull request by kelsoncm**
Hi, @mdjnelson !

This error occurs because when there a mandatory field in the users profile, the JOINs with the 'user custom field' table's must be included. As Moodle already has the solution ready for this, in this patch I used the native solution..

I hope it helps.

See: https://github.com/mdjnelson/moodle-mod_customcert/issues/512

### CODE REVIEW

**Review by atexeira — APPROVED** [review]
This update solve the problem.

**Comment by mdjnelson** [comment]
Thanks for your work on this. Will merge when I am at my computer.

**Comment by mdjnelson** [comment]
Computer wasn't playing nice but all sorted now with new battery (I hope). Will get this done tonight (Perth time).

**Comment by mdjnelson** [comment]
Sorry I am not sure why I closed this. Getting confused from all the similar issues.

**Comment by mdjnelson** [comment]
I pushed this commit to 4.0. However, this was already fixed by https://github.com/mdjnelson/moodle-mod_customcert/issues/465 but this SQL is nicer which is why I am using it now.

**Pull request closed without merging**
