### PR TITLE
Adapt mobile app code to Ionic 5

### PR DESCRIPTION
**Pull request by dpalou**

### CODE REVIEW

**Comment by mdjnelson** [comment]
You legend Dani, thanks! Should I backport this to my other supported branches?

**Comment by dpalou** [comment]
Hi Mark! IMO yes, I didn't know which branches you supported so I sent it only to the latest.

**Comment by jleyva** [comment]
Hey @mdjnelson 

could you merge this PR as soon you have availability? 
We'd need to deploy the new version in MoodleCloud and point our site administrators to the correct branch so they can update the plugin.

The new app version of the app is being released this week, so hopefully site admins will have time to upgrade

**Comment by mdjnelson** [comment]
Done, thanks a lot guys! I have put this on the 3.11, 3.10 and 3.9 branch.

**Pull request closed without merging**
