### PR TITLE
Added element to show text assignment answers in certificate

### PR DESCRIPTION
**Pull request by yorickreum**
We added an element to show text assignment answers in certificate. Our main use case for this is to enable our students to fill some parts of the certificate on their own. This is probably useful for other institutions, too.

### CODE REVIEW

**Comment by mdjnelson** [comment]
Thanks for providing this! Before I begin reviewing however can you fix the issues Travis has detected? :)

**Comment by yorickreum** [comment]
Sure thing. I just didn't get into the office the last week. I now fixed the Travis errors and added some extra lines to be sure that only suitable assignments (with online text answered enabled) are displayed for selection.

**Comment by yorickreum** [comment]
I now also added a fallback if the selected assignment can not be found in the database, e.g. if the assignment was deleted after adding it to the certificate.

**Comment by yorickreum** [comment]
Here are the strings translated to German, if you want to add them:

`$string['assignmentanswer'] = 'Aufgabenantwort';
$string['assignmentanswer_help'] = 'Die Antwort auf die ausgewählte Aufgabe wird auf dem PDF angezeigt. Es werden nur Aufgaben angezeigt, die online Textabgaben aktiviert haben.';
$string['noassignmentanswer'] = 'Diese Aufgabe wurde bisher nicht beantwortet.';
$string['assignmentnotfound'] = 'Die Aufgabe konnte im Kurs nicht gefunden werden.';
$string['pluginname'] = 'Aufgabenantwort';
$string['privacy:metadata'] = 'Das "Assignment answer"-Plugin speichert keine personenbezogenen Daten.';`

**Comment by mdjnelson** [comment]
There still seems to be failures - https://travis-ci.org/mdjnelson/moodle-mod_customcert/builds/647271480?utm_source=github_status&utm_medium=notification.

**Comment by yorickreum** [comment]
Sorry, one empty line too much… Fixed it.

**Comment by kaysi405** [comment]
> 
> 
> We added an element to show text assignment answers in certificate. Our main use case for this is to enable our students to fill some parts of the certificate on their own. This is probably useful for other institutions, too.

I agree, it seems very useful. Is it possible to use this "element" now or in the new future?

**Comment by mdjnelson** [comment]
The code is already available so you can install it now if you want. See https://github.com/mdjnelson/moodle-mod_customcert/pull/320/files.

@yorickreum have you considered putting this on https://moodle.org/plugins/browse.php?list=category&id=73 in the meantime then writing a forum post on https://moodle.org/mod/forum/view.php?id=7163?

**Comment by mdjnelson** [comment]
I've decided not to include this in the core plugin as it is very specific. I suggest adding it the database I listed above and advertising it on the forums. Thanks!

**Pull request closed without merging**
