### PR TITLE
Add new element to display course short name

### PR DESCRIPTION
**Pull request by emyb2**
This element is based on the coursename element, and provides the ability to display the course shortname on certificates

### CODE REVIEW

**Comment by emyb2** [comment]
I hope that this is a pretty straight forward PR as I would very much appreciate this to be added to the main activity module :)

**Comment by mdjnelson** [comment]
Thanks Donald. I have added it to my to-do list (keep in mind I no longer work at Moodle HQ).

**Comment by emyb2** [comment]
Thanks Mark. I will await the pulling of this pull request :)

**Comment by mdjnelson** [comment]
Just thinking .. instead of adding another element, perhaps we could edit the existing element to have a select box where you can choose the full name or the short name. Thoughts?

**Comment by emyb2** [comment]
Sounds good. That would be dryer.

**Comment by mdjnelson** [comment]
Would you be willing to code it? :)

**Comment by emyb2** [comment]
Haha was waiting for this. I can have a crack at it ;) any existing element you have in mind I can use to base it off?

**Comment by mdjnelson** [comment]
The grade element has a field to choose what grade item to choose, that's a good start. Cheers!

**Comment by mdjnelson** [comment]
I created #415, closing.

**Pull request closed without merging**
