### PR TITLE
Issue #531: Email task performance improvements and time limit

### LINKED ISSUE #531: CPU % runs high even on an idle server caused by Custom Cert email task
Moodle 4.1 and Moodle 4.0
Custom Cert Version 4.02  2022041902

CPU % runs high even on an idle server caused by Custom Cert email task.

The CPU % ranges from 0% to 3% on an idle machine with the Custom Cert email task disabled.
Mostly sits at 0%

The CPU % ranges from 8% - 15% on an idle machine with the Custom Cert email task enabled.
The CPU never stops and operates at a minimum of 8%

I noticed the change when I updated from 3.7 to 4.0.    I went from 3.7 to 3.9 to 3.11 then to 4.0 and 4.1.

The Email task does not report any errors but the time to complete each task is taking about 20 seconds.
 
image

I have this running on both an 4-5 year old AWS Linux 2 LAMP and a new AWS Bitnami Moodle site. 

This does not seem like correct behavior.

Thank for your help.

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #531

### CODE REVIEW

**Comment by Peterburnett** [comment]
Hi @mdjnelson, just checking in on this one, and if you had any feedback. I can deploy on a fork, but I would rather not where it can be avoided.

 It would be ideal if I could include this in my next client deployment in 2-3 weeks

**Comment by mdjnelson** [comment]
Sorry @Peterburnett i've been focusing on other issues and am free to look now. Also, please see there is another improvement for this at https://github.com/mdjnelson/moodle-mod_customcert/pull/610. Feel free to have a look and comment with what you think. :)

**Comment by mdjnelson** [comment]
Hi Peter,

I don't think it is safe to assume just because the user accessed the course after the last time the task was run that they would have necessarily downloaded the certificate.

What are your thoughts?

**Comment by mdjnelson** [comment]
Closing this in favour of https://github.com/mdjnelson/moodle-mod_customcert/pull/610 and due to my comments above.

**Pull request closed without merging**
